name: Refresh Discord Widget

on:
    schedule:
        - cron: '0 6 * * *'
    workflow_dispatch: {}

jobs:
    refresh:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - run: npm ci
            - run: npm start
              env:
                  GH_STATS_USERNAME: ${{ secrets.GH_STATS_USERNAME }}
                  GH_PAT: ${{ secrets.GH_PAT }}
                  DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
                  DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
                  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
